name: Release TorchVision Models for TorchExpo
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: ""
jobs:
  script-and-publish:
    strategy:
      matrix:
        task:
          ["image-classification", "semantic-segmentation", "object-detection"]
    runs-on: ubuntu-latest
    env:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      VERSION: ${{ github.event.inputs.version }}
      TASK: ${{ matrix.task }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.4"
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute script
        run: python script_and_publish.py
